Acardynamique_version_stand_alone/acar.2.4.3/routes/acar.py
from flask import Blueprint, Flask, render_template, request, redirect, url_for, current_app, flash,jsonify
import os,sys,time
from datetime import datetime , timedelta
from copy import deepcopy


# Récupérer le chemin du répertoire principal du projet


project_path = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(project_path)
from fonctions.chrono import *
from fonctions.init_reset_acar import *
from donnees_acars.donnees_acar1 import *
from donnees_acars.donnees_acar3 import *



acar_bp = Blueprint('acar', __name__)

    


@acar_bp.route("/acar/id_acar=<int:id_acar>/slide=<int:slide>")
def f_acar(id_acar, slide):
    init_donnees(id_acar)

    if current_app.config['acar_'+str(id_acar)]['chronos'][0]['temps_depart'] == 0 :

        current_app.config['acar_'+str(id_acar)]['chronos'][0]['temps_depart'] =  time.perf_counter()
        current_app.config['acar_'+str(id_acar)]['chronos'][0]['pause']='false'

    donnees = current_app.config['acar_'+str(id_acar)]['donnees']
    id_acar = current_app.config['acar_'+str(id_acar)]['id_acar']
    titre_acar = current_app.config['acar_'+str(id_acar)]['titre_acar']
    sabliers= deepcopy(current_app.config['acar_'+str(id_acar)]['sabliers'])
    for id,sablier in sabliers.items():
        sablier['duree_restante']=convertir_secondes_en_hms(sablier['duree_restante'])
    chronos= deepcopy(current_app.config['acar_'+str(id_acar)]['chronos'])
    for id,chrono in chronos.items():
        chrono['temps_ecoule']=convertir_secondes_en_hms(chrono['temps_ecoule'])
    decisions = deepcopy(current_app.config['acar_'+str(id_acar)]['decisions'])
    

    return render_template("acar"+str(id_acar)+"/acar"+str(id_acar)+"_"+str(slide)+".html",
                                            donnees = donnees,
                                            sabliers = sabliers,
                                            chronos =  chronos,
                                            id_acar = id_acar,
                                            titre_acar = titre_acar,
                                            decisions = decisions,
                                            slide = slide
                                            )
                                        

Acardynamique_version_stand_alone/acar.2.4.3/routes/index.py
from flask import Blueprint, Flask, render_template, request, redirect, url_for, session,flash

main_bp = Blueprint('main', __name__ )



@main_bp.route("/")
def index():
    return render_template("index.html")

Acardynamique_version_stand_alone/acar.2.4.3/templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mon appli</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet"  href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
 

    

    {% block css %}
   
    {% endblock %}
</head>
<body>
    
    {% block gestion_son %}
   
    {% endblock %}
  <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
    

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <img src="{{ url_for('static', filename='img/logo.png') }}" alt="logo" width="50">
    <a class="navbar-brand" href="#">Acar Dynamique</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
       
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.index') }}">Accueil</a>
        </li>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Liste des ACARS
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="nav-link" href="{{ url_for('acar.f_acar', id_acar=1,slide=1) }}">Premier test d'Acar</a></li>
            <li><a class="nav-link" href="{{ url_for('acar.f_acar', id_acar=3,slide=1) }}">Arrêt cardiaque au bloc opératoire</a></li>
            
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
    {% block ident %}{% endblock %}
    <div id="container">
      {% block header %}{% endblock %}
    </div>
    <div id="container">
        {% block content %}{% endblock %}
    </div>
    <script src="{{ url_for('static', filename='js/jquery-3.7.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
    {% block footer %}{% endblock %} 
    
</body>
</html>

Acardynamique_version_stand_alone/acar.2.4.3/templates/content_generique_acar.html
<div class="container">
    
        
    {% for id, tache in donnees.items() if tache['slide'] == slide%}
    <div class="row">
  
        <div class="col">
          <form onsubmit="modifier(event, {{id}},{{id_acar}},{{slide}})">
                
                    <button id="id_bouton_tache{{ id }}" type="submit" class="btn btn-primary btn-block w-100 fixed-height-button custom-button accomplie-{{ tache['accomplie'] }}">
                        {{ tache['label'] }}
                    </button>
            
            </form>
            {% if tache['commentaire']: %}
            <p> {{ tache['commentaire'] }}</p>
            {% endif %}

        </div>
  
  
  
        
    {% if tache['sablier']: %}
  
    
        <div class="col">
            <button id="id_bouton_sablier{{ id }}" type="submit" class="btn btn-primary btn-block w-100 fixed-height-button custom-button accomplie-{{ tache['accomplie'] }}">
                <span id = "id_valeur_sablier{{id}}"></span> 
            </button>
        </div>
        
    {% if sabliers[id]['repetition']>1 and tache['sablier']==1 : %}
        <div class="col">
          <button id="id_bouton_sablier_restant{{ id }}" type="submit" class="btn btn-primary btn-block w-100 fixed-height-button custom-button accomplie-{{ tache['accomplie'] }}">
              <span id = "valeur_sablier_restant{{id}}"></span> 
          </button>
          <p>Nombre de répétitions restantes </p> 
      </div>
      {% endif %}
  
    {% endif %}
  
   
    {% if tache['chrono']: %}
  
        <div class="col">
            <button id="id_bouton_chrono{{ tache['id'] }}" type="submit" class="btn btn-primary btn-block w-100 fixed-height-button custom-button accomplie-{{ tache['accomplie'] }}">
                <span id = "id_valeur_chrono{{tache['id']}}"></span> 
            </button>
        </div>
  
  
  
    {% endif %}
  
    
  </div>
  <p></p>
    {% endfor %}
      
    
</div>
    

Acardynamique_version_stand_alone/acar.2.4.3/templates/footer_acar.html
<script>
    maj(id_acar,slide);
    
    setInterval(() => {
        
        maj(id_acar,slide);
        decision(id_acar,slide);
        
    }, 1000);
</script>

Acardynamique_version_stand_alone/acar.2.4.3/templates/gestion_son.html
{% for id, tache in donnees.items() if  tache['slide'] == slide %}
    {%if  'sound' in tache%}
    <audio id="audio_tache{{id}}" class="audio"  controls>
        <source src="{{ url_for('static', filename='sounds/'+tache['sound']) }}" type="audio/mp3">
        Votre navigateur ne prend pas en charge l'élément audio.
    </audio>
    {%endif %}
    {% if id in sabliers%}
        {% if sabliers[id]['sound']%}
        <audio id="audio_sablier{{id}}" class="audio"  controls>
            <source src="{{ url_for('static', filename='sounds/'+sabliers[id]['sound']) }}" type="audio/mp3">
            Votre navigateur ne prend pas en charge l'élément audio.
        </audio>
        {%endif %}
    {%endif %}
{% endfor %}
<script>
    var audios = {};
    document.addEventListener("DOMContentLoaded", function() {
        {% for id, tache in donnees.items() if tache['slide'] == slide  %}
            {%if  'sound' in tache%}

            var audioElement = document.getElementById("audio_tache{{ id }}");
            if (audioElement) {
                console.log('il y a bien une tache son', '{{ tache["sound"] }}');
                audios["audio_tache{{ id }}"] = audioElement;
                }
            {%endif %}
            {%if  'sound' in sabliers[id]%}

            var audioElement = document.getElementById("audio_sablier{{ id }}");
            if (audioElement) {
                console.log('il y a bien une tache son', '{{ sabliers[id]["sound"] }}');
                audios["audio_sablier{{ id }}"] = audioElement;
                }
            {%endif %}

        {% endfor %}
        console.log(audios);
    });
</script>

Acardynamique_version_stand_alone/acar.2.4.3/templates/header_acar.html
<div class="container">
    <div class="row">
        <div class="col-6">
            <h2 class="text-center"> {% block title %} {{titre_acar}}  {% endblock %}</h2>
          </div>

          
        <div class="col-sm">
          <div class="alert alert-primary" role="alert">
              <h4 class="text-center" >Slide {{slide}}</h4>
            </div>
          
          <p></p>
           
        </div>
      <div class="col-sm">
        <div class="alert alert-primary" role="alert">
            <h4 class="text-center" >Timer : <span  id="id_valeur_chrono0"></span></h4>
          </div>
       
        <p></p>
       
      </div>
      
      <div class="col-sm">
        <div class="alert alert-primary" role="alert">
            <form onsubmit="reset_acar(event,{{id_acar}})">
                <div class="d-grid gap-2 col-12 mx-auto">
                    <button id="button_reset_{{id_acar}}" type="submit" class="btn btn-primary">
                        reset ACAR {{id_acar}}
                    </button>
                </div>
            </form>
        </div>
       
        <p></p>
       
      </div>
      
    </div>
  </div>

Acardynamique_version_stand_alone/acar.2.4.3/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Accueil</h1>
<p> bienvenue sur ACAR !</p>
{% endblock %}